name: .NET Build and Publish

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache@v3
      with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            win-nuget
    - name: Publish Windows
      run: | 
        dotnet publish ./kvexplorer.Desktop/kvexplorer.Desktop.csproj --configuration Release --runtime win-x64 --output ${{ github.workspace }}\artifacts\win-x64 -f net8.0-windows10.0.19041.0
        $files = Get-ChildItem -Path "$env:GITHUB_WORKSPACE\artifacts\win-x64"  -Exclude @("*.pdb", "*.dsym","Key Vault Explorer") 
        Compress-Archive -Path $files -DestinationPath "$env:GITHUB_WORKSPACE\artifacts\win-x64.zip"
      shell: pwsh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win
        path: ${{ github.workspace }}\artifacts\win-x64.zip
      
  build_macos_intel:
    name: Build macOS_intel
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache@v3
      with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            mac-nuget
    - name: publish_macOS_intel
      run: |
        dotnet publish ./kvexplorer.Desktop/kvexplorer.Desktop.csproj --configuration Release --runtime osx-x64 --output "$($env:GITHUB_WORKSPACE)\artifacts\osx-x64" -f net8.0
        $initialRootDir = "Key Vault Explorer"
        $contentsDir = "$initialRootDir\Contents"
        $macOSDir = "$($initialRootDir)\Contents\MacOS"
        $resourcesPath = "$($initialRootDir)\Contents\Resources"
        New-Item -ItemType Directory -Path $initialRootDir -Force | Out-Null
        New-Item -ItemType Directory -Path $contentsDir -Force | Out-Null
        New-Item -ItemType Directory -Path $macOSDir -Force | Out-Null
        New-Item -ItemType Directory -Path $resourcesPath -Force | Out-Null
        New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE\final" -Force | Out-Null
        Copy-Item -Path -Path "$($env:GITHUB_WORKSPACE)\artifacts\osx-x64" -Destination $macOSDir -Force -Recurse -Exclude @("*.pdb") 
        Copy-Item -Path "$env:GITHUB_WORKSPACE/kvexplorer/Assets/Info.plist" -Destination $contentsDir -Force
        Copy-Item -Path "$env:GITHUB_WORKSPACE/kvexplorer/Assets/AppIcon.icns" -Destination $resourcesPath -Force
        Rename-Item -Path $initialRootDir -NewName "$($initialRootDir).app" -Force 
        Move-Item -Path "$($initialRootDir).app" -Destination "$env:GITHUB_WORKSPACE\final\$($initialRootDir).app"
        # Compress-Archive -Path "$($initialRootDir).app" -DestinationPath "$env:GITHUB_WORKSPACE\final\mac-x64.zip"
        Get-ChildItem -Recurse
        Rename-Item -Path  "$($initialRootDir).app" -NewName "x64_$($initialRootDir).app"  -Force 
      shell: pwsh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS_x64
        path: ${{ github.workspace }}/final/

  build_macos:
    name: Build macOS_arm
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache@v3
      with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            mac-nuget
    - name: Publish macOS Arm
      run: | 
        dotnet publish ./kvexplorer.Desktop/kvexplorer.Desktop.csproj --configuration Release --runtime osx-arm64 --output "$($env:GITHUB_WORKSPACE)\artifacts\osx-arm64" -f net8.0
        $initialRootDir = "Key Vault Explorer"
        $contentsDir = "$initialRootDir\Contents"
        $macOSDir = "$($initialRootDir)\Contents\MacOS"
        $resourcesPath = "$($initialRootDir)\Contents\Resources"
        New-Item -ItemType Directory -Path $initialRootDir -Force | Out-Null
        New-Item -ItemType Directory -Path $contentsDir -Force | Out-Null
        New-Item -ItemType Directory -Path $macOSDir -Force | Out-Null
        New-Item -ItemType Directory -Path $resourcesPath -Force | Out-Null
        
        Copy-Item -Path -Path "$($env:GITHUB_WORKSPACE)\artifacts\osx-arm64" -Destination $macOSDir -Force -Recurse -Exclude @("*.pdb") 

        Copy-Item -Path "$env:GITHUB_WORKSPACE/kvexplorer/Assets/Info.plist" -Destination $contentsDir -Force
        Copy-Item -Path "$env:GITHUB_WORKSPACE/kvexplorer/Assets/AppIcon.icns" -Destination $resourcesPath -Force
        Rename-Item -Path $initialRootDir -NewName "$($initialRootDir).app" -Force 

        Move-Item -Path "$($initialRootDir).app" -Destination "$env:GITHUB_WORKSPACE\final\$($initialRootDir).app"

        # Compress-Archive -Path "$($initialRootDir).app" -DestinationPath "$env:GITHUB_WORKSPACE\final\mac-arm64.zip"
        Get-ChildItem -Recurse

      shell: pwsh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS_arm64
        path: ${{ github.workspace }}/final/mac-arm64.zip
        
  release:
    name: Release code
    needs: [ build_macos, build_windows, build_macos_intel]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Download built artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        run: |
          Get-ChildItem -Recurse
          gh release create v0.0.${{github.run_attempt}} --draft
          gh release upload v0.0.${{github.run_attempt}} "$env:GITHUB_WORKSPACE/win/win-x64.zip" "$env:GITHUB_WORKSPACE/macOS_arm64/mac-arm64.zip" "$env:GITHUB_WORKSPACE/macOS_x64/mac-x64.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
      
      

        
