name: .NET Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ dev ]

permissions:
  contents: write

jobs:

  build:
    strategy:
      matrix:
        os: [windows-latest]
        # os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache@v3
      with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
    - name: Publish Windows
      if: matrix.os == 'windows-latest'
      run: dotnet publish ./kvexplorer.Desktop/kvexplorer.Desktop.csproj --configuration Release --runtime win-x64 --output ${{ github.workspace }}\artifacts\win-x64 -f net8.0-windows10.0.19041.0
      
    # - name: Publish Linux
    #   if: matrix.os == 'ubuntu-latest'
    #   run: dotnet publish ./kvexplorer.Desktop/kvexplorer.Desktop.csproj --configuration Release --self-contained true --runtime linux-x64 --output ../artifacts/linux-x64
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: ${{ github.workspace }}\artifacts\
   
    - name: Create Release
      run: |
        Get-ChildItem -Recurse
        Compress-Archive -Path "$env:GITHUB_WORKSPACE\artifacts\win-x64" -DestinationPath "$env:GITHUB_WORKSPACE\artifacts\kvexplorer-win-x64.zip"
        gh release create v0.0.${{github.run_attempt}} --draft
        gh release upload v0.0.${{github.run_id}} "$env:GITHUB_WORKSPACE\artifacts\kvexplorer-win-x64.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
    
      

        
